### ISSUE TITLE
showing items in chat

### ISSUE THREAD

**Issue by LuckserSky34** [Warsteiner37/GreenJobs#1]
add an placeholder to show if a player is in specific job or not

**Comment by Warsteiner37** [comment]
> add an placeholder to show if a player is in specific job or not

You mean a true/false output?

**Comment by LuckserSky34** [comment]
exactly

**Comment by Warsteiner37** [comment]
> exactly
 
^added in 1.1.5 see  https://github.com/Warsteiner37/GreenJobs/wiki/PlaceHolderAPI
